name: Windows Test Release

run-name: >-
  ${{
    github.event_name == 'workflow_dispatch' && format('Windows Test Release - v{0}', github.event.inputs.tag) ||
    format('Windows Test Release - {0}', github.ref_name)
  }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag Version (e.g. 1.0.0)'
        required: true
        type: string

jobs:
  # Set version first
  set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Version Variable
        id: set_version
        run: |
          # Print debug info
          echo "Event name: ${{ github.event_name }}"

          # Always use version number without v prefix
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.tag }}"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            VERSION="test-${{ github.event.number }}"
          else
            # Get version from tag (remove v prefix if present)
            TAG="${GITHUB_REF_NAME}"
            VERSION="${TAG#v}"
          fi

          # Ensure VERSION is not empty, default to 1.0.0
          if [ -z "$VERSION" ]; then
            echo "WARNING: Empty version, using default test-1.0.0"
            VERSION="test-1.0.0"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Set version: $VERSION"

  # Update Tauri Config Version
  update-version:
    runs-on: ubuntu-latest
    needs: set-version
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Tauri Config Version
        run: |
          echo "Current version: ${{ needs.set-version.outputs.version }}"
          # Update version using jq
          jq '.version = "${{ needs.set-version.outputs.version }}"' app/src-tauri/tauri.conf.json > tmp.json && mv tmp.json app/src-tauri/tauri.conf.json
          echo "Updated tauri.conf.json:"
          cat app/src-tauri/tauri.conf.json

      - name: Commit and Push Updated Version
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add app/src-tauri/tauri.conf.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "[ci skip] Update version to ${{ needs.set-version.outputs.version }}"
            git push
          fi

      - name: Upload tauri.conf.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-config
          path: app/src-tauri/tauri.conf.json

  # Windows Platform Build Task
  publish-windows:
    needs: [set-version, update-version]
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - variant: 'cpu'
            features: '--features whisper-cpu'
          - variant: 'cuda'
            features: '--features whisper-cuda'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download tauri.conf.json
        uses: actions/download-artifact@v4
        with:
          name: tauri-config
          path: app/src-tauri/

      - name: Install CUDA Toolkit (Windows CUDA)
        if: matrix.variant == 'cuda'
        uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
        with:
          cuda: '12.5.0'
          method: 'network'
          sub-packages: '[ "nvcc", "cudart", "cublas", "cublas_dev", "curand", "curand_dev", "nvrtc", "nvrtc_dev", "visual_studio_integration", "thrust" ]'

      - name: Set CUDA environment variables (Windows CUDA)
        if: matrix.variant == 'cuda'
        run: |
          echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          echo "CUDA_PATH=${{steps.cuda-toolkit.outputs.CUDA_PATH}}" >> $GITHUB_ENV
          echo "${{steps.cuda-toolkit.outputs.CUDA_PATH}}\bin" >> $GITHUB_PATH
          nvcc -V


      - name: Fix CUDA Visual Studio Integration
        if: matrix.variant == 'cuda'
        run: |
          $cudaPath = "${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          echo "CUDA Path: $cudaPath"

          # Source: CUDA Visual Studio integration files
          $sourceDir = "$cudaPath\extras\visual_studio_integration\MSBuildExtensions"
          echo "Source: $sourceDir"

          # Find Visual Studio installation
          $vsPaths = @(
            "C:\Program Files\Microsoft Visual Studio\2022\Enterprise",
            "C:\Program Files\Microsoft Visual Studio\2022\Community",
            "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
          )

          foreach ($vsPath in $vsPaths) {
            $destDir = "$vsPath\MSBuild\Microsoft\VC\v170\BuildCustomizations"
            if (Test-Path $destDir) {
              echo "Found VS at: $vsPath"
              echo "Destination: $destDir"

              if (Test-Path $sourceDir) {
                echo "Copying CUDA integration files..."
                Copy-Item "$sourceDir\*" $destDir -Force -Verbose
                echo "Successfully copied CUDA integration files to $destDir"
              } else {
                echo "ERROR: Source directory not found: $sourceDir"
              }
              break
            }
          }

          # Set environment variable for CMake to use CUDA toolset
          echo "CMAKE_GENERATOR_TOOLSET=cuda=$cudaPath" >> $GITHUB_ENV

      - name: Fix version format for Windows MSI
        run: |
          $versionJson = Get-Content -Path app/src-tauri/tauri.conf.json | ConvertFrom-Json
          $currentVersion = $versionJson.version

          if ($currentVersion -match '-(.+)$') {
            $newVersion = $currentVersion -replace '-(.+)$', ''

            $versionJson.version = $newVersion

            $jsonContent = Get-Content -Path app/src-tauri/tauri.conf.json -Raw
            $jsonContent = $jsonContent -replace '"version": "([^"]+)"', "`"version`": `"$newVersion`"" -replace '"version": "([^"]+)"', "`"version`": `"$newVersion`""
            $jsonContent | Set-Content -Path app/src-tauri/tauri.conf.json -NoNewline

            echo "Windows version $currentVersion changed to $newVersion"
          } else {
            echo "Version $currentVersion does not need to be modified"
          }

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Increase Node.js memory limit
        run: |
          echo "NODE_OPTIONS=--max-old-space-size=4096" >> $GITHUB_ENV

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: app/src-tauri
          cache-on-failure: true

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Install Dependencies
        run: |
          bun install
          cd app && bun install


      # Copy CUDA config for CUDA builds (with installer checks)
      - name: Use CUDA config (Windows CUDA)
        if: matrix.variant == 'cuda'
        run: |
          Copy-Item "app\src-tauri\tauri.cuda.conf.json" "app\src-tauri\tauri.conf.json" -Force
          echo "Using CUDA configuration with installer CUDA detection"

      # Build Windows App (without publishing)
      - name: Build Windows App (${{ matrix.variant }})
        run: |
          cd app
          echo "Starting Windows ${{ matrix.variant }} build..."
          ../node_modules/.bin/tauri build --no-bundle ${{ matrix.features }}
          echo "Windows ${{ matrix.variant }} build completed successfully!"
          echo "Build artifacts location: src-tauri/target/release/"
          Get-ChildItem src-tauri/target/release/